version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: driver-helper-frontend
    restart: always
    ports:
      - 8081:80
    depends_on:
      - driver-helper-backend
    networks:
      - driver-network

  nginx:
    image: nginx:1.19.0-alpine
    container_name: driver-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 3080:80
    depends_on:
      - frontend
    networks:
      - driver-network

networks:
  driver-network:
    external:
      name: docker-compose-backend_driver-network